### ISSUE TITLE
👀  `outputs.prerelease`

### ISSUE THREAD

**Issue by unicornware** [flex-development/dist-tag-action#23]
## Describe the ideal solution or feature request

this action should set an additional output, `prerelease`.

the value of the output should be based on dist tag length. a length of `0` implies latest, whereas ` length > 0` implies prerelease.

## Impact, usage, and difficulty

| User goals                            | Usage frequency                    | Difficulty scale                                |
| ------------------------------------- | ---------------------------------- | ----------------------------------------------- |
| ie. What the user wants to accomplish | ie. Daily, weekly, monthly, yearly | ie. Scale of 1 - 5 (filled out post submission) |
| add `prerelease` field to action output                                     | weekly/monthly                                 | `1`                                              |

## How does this tie into our current product?

one of the target audiences for this action are [gh cli][1] users: `outputs.tag` can be used to determine prerelease state when [creating a release][2]. users, however, must define a `prerelease` output in their workflow before this feature can be fully taken advantage of:

```yaml
      - id: prerelease
        name: Check for prerelease
        run: echo "::set-output name=result::${{ steps.dist-tag.outputs.tag != '' }}"
      ...
      - id: publish
        name: Publish release
        run: gh release create $TAG *.tgz -t=$TAG -F=$NOTES_FILE -p=${{ steps.prerelease.outputs.result }}
```
> see the [current release workflow][3] for a full example.

even though users can set outputs themselves, this feature would improve user experience by providing users with an opportunity to remove any logic specific to determining prereleases.

[1]: https://cli.github.com
[2]: https://cli.github.com/manual/gh_release_create
[3]: https://github.com/flex-development/dist-tag-action/blob/1.0.1-alpha.3/.github/workflows/release.yml
